version: '3.8'

services:
  api:
    build: ./src/api
    ports:
      - "8000:8000"
    volumes:
      - ./model:/app/model

  frontend:
    build: ./src/frontend
    ports:
      - "8501:8501"
    depends_on:
      - api
